# Project Information
site_name: PagerDuty HowTos and Tutorials
site_description: A collection of tutorials and user documentation for improving your PagerDuty experience.
site_author: PagerDuty, Inc.
site_url: https://howdoi.pagerduty.com/

# Repository
repo_url: https://github.com/pagerduty/iwantto-tutorial-docs

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme:
  name: pagerduty
  title: 'HowTos and Tutorials'

# Contents
nav:
  - Home: 'index.md'
  - Improve MTTR:
    - Incident Workflows: 'features/iworkflows.md'
    - Event Orchestration: 'features/eo.md'
  - Alert Fatigue:
    - Content-Based Alert Grouping: 'features/agrouping'
    - Intelligent Alert Grouping: 'features/igrouping'
    - Global Alert Grouping: 'features/ggrouping'
  - Gain Visibility:
    - Service Graph: 'features/sgraph.md'
    - Business Service Subscriptions: 'features/bizsubs.md'
    - Status Pages: 'features/spages.md'

# Analytics
google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - pymdownx.tabbed:

# Development URL, bind to local only.
dev_addr: '127.0.0.1:8000'
